---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ubuntu-trusty
    alias: ubuntu/trusty
  - name: ubuntu-xenial
    alias: ubuntu/xenial
  - name: ubuntu-bionic
    alias: ubuntu/bionic
  - name: ubuntu-cosmic
    alias: ubuntu/cosmic
  - name: debian-jessie
    alias: debian/jessie
  - name: debian-stretch
    alias: debian/stretch
  - name: debian-buster
    alias: debian/buster
  - name: debian-sid
    alias: debian/sid

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
